"""Beancount write helpers: compose snippets, validate them, and append atomically.

This module provides create_* functions used by the CLI to persist entities to
beancount include files using the temp-file -> validate -> append pattern.

Notes:
- Single-user assumptions: no file locking is implemented.
- Validation is snippet-only by default (parser.parse_string). Use
  `ledger validate` for full-ledger validation.
"""
from __future__ import annotations
from pathlib import Path
import tempfile
import uuid
import os
import json
from datetime import date, datetime
from typing import Optional, List

from . import config, models, beancount_store


def _write_and_fsync(f, data: str):
    f.write(data)
    f.flush()
    os.fsync(f.fileno())


def _atomic_append(target: Path, snippet: str) -> None:
    # Append snippet to target with a single append+fsync. Target must exist.
    # Ensure newline separation
    mode = "a"
    with open(target, mode, encoding="utf-8") as f:
        if f.tell() != 0:
            # ensure previous file ends with newline
            f.seek(0, os.SEEK_END)
            f.write("\n")
        _write_and_fsync(f, snippet + "\n")


def _validate_snippet(snippet: str) -> List[str]:
    # Use beancount.parser.parser.parse_string for snippet-only validation
    from beancount.parser import parser

    res = parser.parse_string(snippet)
    # parser may return (entries, errors, ...) across versions
    errors = res[1] if len(res) > 1 else []
    return list(errors)


def _temp_validate_snippet(snippet: str, dirpath: Path) -> List[str]:
    # Write snippet to a temp file on same filesystem (dirpath) and validate
    fname = dirpath / f".tmp-{uuid.uuid4().hex}.beancount"
    with open(fname, "w", encoding="utf-8") as f:
        _write_and_fsync(f, snippet)
    try:
        errs = _validate_snippet(snippet)
        return errs
    finally:
        try:
            fname.unlink()
        except Exception:
            pass


# ID allocation helpers

def _next_custom_id_for(kind: str, id_field: str) -> int:
    # Use beancount_store listing to find current max id and increment
    if kind == "customer":
        items = beancount_store.list_customers()
    elif kind == "creditor":
        items = beancount_store.list_creditors()
    elif kind == "payment_account":
        items = beancount_store.list_payment_accounts()
    else:
        items = []
    max_id = 0
    for it in items:
        if getattr(it, "id", None) is not None:
            try:
                v = int(it.id)
                if v > max_id:
                    max_id = v
            except Exception:
                continue
    return max_id + 1


# Invoice seq

def _invoice_seq_path() -> Path:
    base = config.get_basedir()
    return base / ".arledge" / "invoice_seq"


def _next_invoice_id() -> int:
    seq = _invoice_seq_path()
    base = config.get_basedir()
    if not seq.exists():
        # attempt recovery: scan existing invoices
        invs = beancount_store.list_invoices()
        max_id = 0
        for inv in invs:
            if inv.id and inv.id > max_id:
                max_id = inv.id
        next_id = max_id + 1
        seq.parent.mkdir(parents=True, exist_ok=True)
        seq.write_text(f"{next_id}\n", encoding="utf-8")
        return next_id
    # Read, increment, write back
    try:
        cur = int(seq.read_text(encoding="utf-8").strip())
    except Exception:
        # Recover from corruption
        invs = beancount_store.list_invoices()
        max_id = 0
        for inv in invs:
            if inv.id and inv.id > max_id:
                max_id = inv.id
        cur = max_id + 1
    # write back next number
    seq.write_text(f"{cur+1}\n", encoding="utf-8")
    return cur


# Create functions

def create_customer(c: models.Customer) -> models.Customer:
    base = config.get_basedir()
    includes = base / "includes"
    includes.mkdir(parents=True, exist_ok=True)
    # Ensure top-level ledger.beancount includes the includes/ files so loader can resolve
    ledger_file = base / "ledger.beancount"
    if not ledger_file.exists():
        ledger_file.write_text(
            '; Top-level ledger file generated by beancount_write\ninclude "includes/customers.beancount"\ninclude "includes/creditors.beancount"\ninclude "includes/payment_accounts.beancount"\ninclude "includes/invoices/*.beancount"\n',
            encoding="utf-8",
        )
    target = includes / "customers.beancount"
    # allocate id if missing
    if c.id is None:
        c.id = _next_custom_id_for("customer", "customer_id")
    # Compose snippet
    today = date.today().isoformat()
    lines = [f"{today} custom \"customer\" \"{c.name}\""]
    if c.id is not None:
        lines.append(f"  customer_id: {c.id}")
    if c.email:
        lines.append(f"  email: \"{c.email}\"")
    if c.address:
        lines.append(f"  address: \"{c.address}\"")
    snippet = "\n".join(lines) + "\n"
    # Validate snippet via temp file in includes dir
    errs = _temp_validate_snippet(snippet, includes)
    if errs:
        raise ValueError(f"Snippet validation failed: {errs}")
    # Append
    if not target.exists():
        target.write_text("", encoding="utf-8")
    _atomic_append(target, snippet)
    return c


def create_creditor(cred: models.Creditor) -> models.Creditor:
    base = config.get_basedir()
    includes = base / "includes"
    includes.mkdir(parents=True, exist_ok=True)
    ledger_file = base / "ledger.beancount"
    if not ledger_file.exists():
        ledger_file.write_text(
            '; Top-level ledger file generated by beancount_write\ninclude "includes/customers.beancount"\ninclude "includes/creditors.beancount"\ninclude "includes/payment_accounts.beancount"\ninclude "includes/invoices/*.beancount"\n',
            encoding="utf-8",
        )
    target = includes / "creditors.beancount"
    if cred.id is None:
        cred.id = _next_custom_id_for("creditor", "creditor_id")
    today = date.today().isoformat()
    lines = [f"{today} custom \"creditor\" \"{cred.name}\""]
    if cred.id is not None:
        lines.append(f"  creditor_id: {cred.id}")
    if cred.email:
        lines.append(f"  email: \"{cred.email}\"")
    if cred.address:
        lines.append(f"  address: \"{cred.address}\"")
    snippet = "\n".join(lines) + "\n"
    errs = _temp_validate_snippet(snippet, includes)
    if errs:
        raise ValueError(f"Snippet validation failed: {errs}")
    if not target.exists():
        target.write_text("", encoding="utf-8")
    _atomic_append(target, snippet)
    return cred


def create_payment_account(pa: models.PaymentAccount) -> models.PaymentAccount:
    base = config.get_basedir()
    includes = base / "includes"
    includes.mkdir(parents=True, exist_ok=True)
    ledger_file = base / "ledger.beancount"
    if not ledger_file.exists():
        ledger_file.write_text(
            '; Top-level ledger file generated by beancount_write\ninclude "includes/customers.beancount"\ninclude "includes/creditors.beancount"\ninclude "includes/payment_accounts.beancount"\ninclude "includes/invoices/*.beancount"\n',
            encoding="utf-8",
        )
    target = includes / "payment_accounts.beancount"
    if pa.id is None:
        # payment accounts reuse global id space via listing
        pa.id = _next_custom_id_for("payment_account", "account_id")
    today = date.today().isoformat()
    lines = [f"{today} custom \"payment_account\" \"{pa.label or pa.identifier or pa.type}\""]
    if pa.id is not None:
        lines.append(f"  account_id: {pa.id}")
    if pa.creditor_id is not None:
        lines.append(f"  creditor_id: {pa.creditor_id}")
    if pa.type:
        lines.append(f"  type: \"{pa.type}\"")
    if pa.label:
        lines.append(f"  label: \"{pa.label}\"")
    if pa.identifier:
        lines.append(f"  identifier: \"{pa.identifier}\"")
    if pa.bank_name:
        lines.append(f"  bank: \"{pa.bank_name}\"")
    if pa.currency:
        lines.append(f"  currency: \"{pa.currency}\"")
    if pa.is_default:
        lines.append(f"  is_default: \"true\"")
    snippet = "\n".join(lines) + "\n"
    errs = _temp_validate_snippet(snippet, includes)
    if errs:
        raise ValueError(f"Snippet validation failed: {errs}")
    if not target.exists():
        target.write_text("", encoding="utf-8")
    _atomic_append(target, snippet)
    return pa


def create_invoice(inv: models.Invoice) -> models.Invoice:
    base = config.get_basedir()
    includes = base / "includes"
    invoices_dir = includes / "invoices"
    invoices_data = invoices_dir / "data"
    invoices_dir.mkdir(parents=True, exist_ok=True)
    invoices_data.mkdir(parents=True, exist_ok=True)
    ledger_file = base / "ledger.beancount"
    if not ledger_file.exists():
        ledger_file.write_text(
            '; Top-level ledger file generated by beancount_write\ninclude "includes/customers.beancount"\ninclude "includes/creditors.beancount"\ninclude "includes/payment_accounts.beancount"\ninclude "includes/invoices/*.beancount"\n',
            encoding="utf-8",
        )
    # allocate invoice id
    if inv.id is None:
        inv.id = _next_invoice_id()
    # write sidecar first
    sidecar_name = f"inv-{inv.id:04d}.json"
    sidecar_path = invoices_data / sidecar_name
    # dump invoice lines to sidecar
    with open(sidecar_path, "w", encoding="utf-8") as f:
        json.dump(config.dump_model(inv), f, indent=2, ensure_ascii=False)
        f.flush()
        os.fsync(f.fileno())
    # compose transaction snippet
    created = (inv.created_at or datetime.now()).date().isoformat()
    title = inv.description or f"Invoice INV-{inv.id:04d}"
    lines = [f"{created} * \"{title}\"", f"  invoice_id: {inv.id}", f"  customer_id: {inv.customer_id}", f"  invoice_data: \"includes/invoices/data/{sidecar_name}\""]
    # postings: use totals from model
    # For simplicity, write a single receivable posting and one income posting + VAT if present
    # Use inv.total and distribution
    # Assets:Receivable:Customer    1250.00 SEK
    currency = inv.currency or "SEK"
    total = inv.total or 0
    subtotal = inv.subtotal or 0
    vat = inv.total_vat or 0
    lines.append(f"  Assets:Receivable:{inv.customer_id}        {total} {currency}")
    lines.append(f"  Income:Services              -{subtotal} {currency}")
    if vat and vat != 0:
        lines.append(f"  Liabilities:VAT               -{vat} {currency}")
    snippet = "\n".join(lines) + "\n"
    # validate snippet
    errs = _temp_validate_snippet(snippet, invoices_dir)
    if errs:
        # remove sidecar if validation fails to avoid orphan
        try:
            sidecar_path.unlink()
        except Exception:
            pass
        raise ValueError(f"Invoice snippet validation failed: {errs}")
    # append to per-month file
    month_file = invoices_dir / f"{created[:4]}-{created[5:7]}.beancount"
    if not month_file.exists():
        month_file.write_text("", encoding="utf-8")
    _atomic_append(month_file, snippet)
    return inv
