import click
import json
import sys
from . import models, config, beancount_store


@click.group()
def cli():
    """Ledger CLI

    AGENTS: run the `arledge instructions` command for detailed agent interaction instructions.

    Machine-actionable JSON is printed to stdout; human-facing messages
    and validation/file errors are printed to stderr. Validation and
    file-read errors exit with a non-zero code (the implementation
    currently uses ``sys.exit(2)`` for these error conditions).

    Environment:
    - Set ARLEDGE_BASEDIR to point to a different project directory if you want
      commands (init, list, create, export) to operate on a specific base
      directory. If unset, commands operate on the current working directory.

    Run the CLI with the project-friendly runner:
      uv run arledge
    """
    pass


@cli.command("init")
@click.option("--force", is_flag=True, default=False, help="Overwrite existing beancount layout if present")
def init(force):
    """Initialize beancount-first directory layout for arledge (ledger.beancount, includes/, .arledge/).

    Creates the following structure in the configured base directory (see ARLEDGE_BASEDIR):

      ledger.beancount
      includes/
        customers.beancount
        creditors.beancount
        payment_accounts.beancount
        invoices/
          YYYY-MM.beancount
          data/
      .arledge/
        invoice_seq

    By default the base directory is the current working directory. To target
    a different directory, set the ARLEDGE_BASEDIR environment variable before
    running the command. Example:

      ARLEDGE_BASEDIR=/path/to/project uv run arledge init

    If files/directories already exist the command will not overwrite them
    unless --force is provided.
    """
    from pathlib import Path
    import datetime

    # Respect ARLEDGE_BASEDIR environment variable if set (see ledger.config.get_basedir())
    cwd = config.get_basedir()
    ledger_file = cwd / "ledger.beancount"
    includes_dir = cwd / "includes"
    includes_customers = includes_dir / "customers.beancount"
    includes_creditors = includes_dir / "creditors.beancount"
    includes_payment_accounts = includes_dir / "payment_accounts.beancount"
    invoices_dir = includes_dir / "invoices"
    invoices_data = invoices_dir / "data"
    arledge_dir = cwd / ".arledge"
    invoice_seq = arledge_dir / "invoice_seq"

    to_create = [includes_dir, invoices_dir, invoices_data, arledge_dir]

    # Check for existing files
    existing = []
    for p in [ledger_file, includes_customers, includes_creditors, includes_payment_accounts, invoices_dir, invoices_data, invoice_seq]:
        if p.exists():
            existing.append(str(p))

    if existing and not force:
        click.echo("Some target files or directories already exist:", err=True)
        for e in existing:
            click.echo(f"  {e}", err=True)
        click.echo("Run with --force to overwrite existing files where applicable.", err=True)
        sys.exit(2)

    # Create directories
    for d in to_create:
        d.mkdir(parents=True, exist_ok=True)

    # Write ledger.beancount with include directives
    ledger_contents = """; Top-level ledger file for arledge - generated by `arledge init`

include "includes/customers.beancount"
include "includes/creditors.beancount"
include "includes/payment_accounts.beancount"
include "includes/invoices/*.beancount"
"""
    ledger_file.write_text(ledger_contents, encoding="utf-8")

    # Write includes files if missing or forced
    if force or not includes_customers.exists():
        includes_customers.write_text(
            """; customers custom directives

; Example:
; 2026-03-01 custom "customer" "ACME Corp"
;   customer_id: 1
;   email: "sales@acme.example"

""",
            encoding="utf-8",
        )
    if force or not includes_creditors.exists():
        includes_creditors.write_text(
            """; creditors custom directives

; Example:
; 2026-03-01 custom "creditor" "Office Supplies Ltd"
;   creditor_id: 1
;   email: "billing@office.example"

""",
            encoding="utf-8",
        )
    if force or not includes_payment_accounts.exists():
        includes_payment_accounts.write_text(
            """; payment accounts custom directives

; Example:
; 2026-03-01 custom "payment_account" "Business Checking"
;   account_id: 1
;   bank: "Nordea"
;   iban: "SE1234567890"
;   currency: "SEK"

""",
            encoding="utf-8",
        )

    # create an empty current-month invoices file as an example
    now = datetime.date.today()
    month_file = invoices_dir / f"{now.year:04d}-{now.month:02d}.beancount"
    if force or not month_file.exists():
        month_file.write_text(
            f"; Invoices for {now.year:04d}-{now.month:02d}\n",
            encoding="utf-8",
        )

    # invoices data dir
    # ensure it's present (created above)

    # invoice_seq
    if force or not invoice_seq.exists():
        invoice_seq.write_text("1\n", encoding="utf-8")

    click.echo(f"Initialized beancount layout at {cwd}", err=True)


@cli.group()
def customer():
    """Customer commands"""
    pass


@customer.command("create")
@click.option("--model", "model_json", default="", help="JSON object for Customer")
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing Customer",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for Customer and exit",
)
def customer_create(model_json, model_file, json_schema):
    """Create a customer from a JSON model or file. Prints created customer JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(
                models.Customer.model_json_schema(), indent=2, ensure_ascii=False
            )
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        c = models.Customer.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid customer JSON: {e}", err=True)
        sys.exit(2)
    # Use beancount write flow
    try:
        from .beancount_write import create_customer

        created = create_customer(c)
    except Exception as e:
        click.echo(f"Failed to create customer: {e}", err=True)
        sys.exit(2)
    # Actionable output: created customer as JSON on stdout
    click.echo(json.dumps(config.dump_model(created), ensure_ascii=False))


@customer.command("list")
def customer_list():
    customers = beancount_store.list_customers()
    if not customers:
        click.echo("No customers", err=True)
        return
    out = [config.dump_model(c) for c in customers]
    click.echo(json.dumps(out, ensure_ascii=False))


@cli.group()
def creditor():
    """Creditor (us) commands"""
    pass


@creditor.command("create")
@click.option("--model", "model_json", default="", help="JSON object for Creditor")
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing Creditor",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for Creditor and exit",
)
def creditor_create(model_json, model_file, json_schema):
    """Create a creditor from a JSON model or file. Prints created creditor JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(
                models.Creditor.model_json_schema(), indent=2, ensure_ascii=False
            )
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        cred = models.Creditor.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid creditor JSON: {e}", err=True)
        sys.exit(2)
    try:
        from .beancount_write import create_creditor

        created = create_creditor(cred)
    except Exception as e:
        click.echo(f"Failed to create creditor: {e}", err=True)
        sys.exit(2)
    click.echo(json.dumps(config.dump_model(created), ensure_ascii=False))


@creditor.command("list")
def creditor_list():
    creds = beancount_store.list_creditors()
    if not creds:
        click.echo("No creditors", err=True)
        return
    out = [config.dump_model(c) for c in creds]
    click.echo(json.dumps(out, ensure_ascii=False))


@creditor.command("view")
@click.argument("creditor_id", type=int)
def creditor_view(creditor_id):
    c = beancount_store.get_creditor(creditor_id)
    if not c:
        click.echo("Creditor not found", err=True)
        sys.exit(2)
    click.echo(json.dumps(config.dump_model(c), ensure_ascii=False))


@creditor.group()
def account():
    """Creditor inbound payment accounts"""
    pass


@account.command("create")
@click.option(
    "--model", "model_json", default="", help="JSON object for PaymentAccount"
)
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing PaymentAccount",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for PaymentAccount and exit",
)
def account_create(model_json, model_file, json_schema):
    """Create a payment account from a JSON model or file. Prints created account JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(
                models.PaymentAccount.model_json_schema(), indent=2, ensure_ascii=False
            )
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        pa = models.PaymentAccount.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid payment account JSON: {e}", err=True)
        sys.exit(2)
    try:
        from .beancount_write import create_payment_account

        created = create_payment_account(pa)
    except Exception as e:
        click.echo(f"Failed to create payment account: {e}", err=True)
        sys.exit(2)
    click.echo(json.dumps(config.dump_model(created), ensure_ascii=False))


@account.command("list")
@click.option("--creditor-id", type=int, default=None)
def account_list(creditor_id):
    rows = beancount_store.list_payment_accounts(creditor_id=creditor_id)
    if not rows:
        click.echo("No payment accounts", err=True)
        return
    out = [config.dump_model(r) for r in rows]
    click.echo(json.dumps(out, ensure_ascii=False))


@cli.group()
def invoice():
    """Invoice commands"""
    pass


@invoice.command("create")
@click.option("--model", "model_json", default="", help="JSON object for Invoice")
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing Invoice",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for Invoice and exit",
)
def invoice_create(model_json, model_file, json_schema):
    """Create an invoice from a JSON model or file. Prints created invoice JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(models.Invoice.model_json_schema(), indent=2, ensure_ascii=False)
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        inv = models.Invoice.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid invoice JSON: {e}", err=True)
        sys.exit(2)
    try:
        from .beancount_write import create_invoice

        created = create_invoice(inv)
    except Exception as e:
        click.echo(f"Failed to create invoice: {e}", err=True)
        sys.exit(2)
    # Include invoice id and invoice_number in actionable JSON
    out = config.dump_model(created)
    out["invoice_number"] = beancount_store.format_invoice_number(created.id)
    click.echo(json.dumps(out, ensure_ascii=False))


@invoice.command("list")
def invoice_list():
    invs = beancount_store.list_invoices()
    if not invs:
        click.echo("No invoices", err=True)
        return
    out = [config.dump_model(inv) for inv in invs]
    click.echo(json.dumps(out, ensure_ascii=False))


@invoice.command("allocate")
def invoice_allocate():
    """Allocate the next invoice id and print it as JSON (id + invoice_number)."""
    try:
        from .beancount_write import allocate_invoice_id
    except Exception as e:
        click.echo(f"Failed to allocate invoice id: {e}", err=True)
        sys.exit(2)
    try:
        nid = allocate_invoice_id()
    except Exception as e:
        click.echo(f"Failed to allocate invoice id: {e}", err=True)
        sys.exit(2)
    out = {"id": nid, "invoice_number": beancount_store.format_invoice_number(nid)}
    click.echo(json.dumps(out, ensure_ascii=False))


@invoice.command("view")
@click.argument("invoice_id", type=int)
def invoice_view(invoice_id):
    inv = beancount_store.get_invoice(invoice_id)
    if not inv:
        click.echo("Invoice not found", err=True)
        sys.exit(2)
    click.echo(json.dumps(config.dump_model(inv), ensure_ascii=False))


@invoice.command("export")
@click.argument("invoice_id", type=int)
@click.option("--format", "fmt", type=click.Choice(["json", "text"]), default="json")
@click.option("--path", default=None)
def invoice_export(invoice_id, fmt, path):
    if fmt == "json":
        out = beancount_store.export_invoice_json(invoice_id, path=path)
        if not out:
            click.echo("Invoice not found", err=True)
            sys.exit(2)
        # actionable output: exported filepath on stdout
        click.echo(out)
    else:
        click.echo("Text export not implemented yet", err=True)
        sys.exit(2)


@cli.group()
def mcp():
    """MCP server commands (stdio transport using FastMCP)."""
    pass


@mcp.command("start")
@click.option("--name", default=None, help="Optional name for the MCP server")
@click.option(
    "--json-response/--no-json-response",
    default=config.MCP_JSON_RESPONSE,
    help="Prefer JSON responses where supported",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Validate configuration and exit without starting the server",
)
def mcp_start(name, json_response, dry_run):
    """Start an MCP stdio server using the official `mcp` library (blocks).

    Example: `uv run arledge mcp start` will block and listen on
    stdin/stdout. Use `--dry-run` to validate imports and configuration
    without blocking (useful for tests).
    """
    # Lazy import to avoid requiring mcp at module import time for unrelated CLI commands
    try:
        from .mcp_server import start_mcp_stdio_server
    except Exception as e:
        click.echo(f"Failed to load MCP server launcher: {e}", err=True)
        sys.exit(2)

    # Call launcher; when not dry-run this will block (mcp.run)
    try:
        start_mcp_stdio_server(name=name, json_response=json_response, dry_run=dry_run)
    except Exception:
        click.echo("Failed to start MCP server", err=True)
        sys.exit(2)


@cli.command()
def instructions():
    """Print instructions for agentic systems on interacting with the CLI."""
    text = """Instructions for agentic systems interacting with the arledge CLI

Overview and machine I/O conventions:
- All machine-actionable outputs (created/listed models, schemas, export file paths) are printed to STDOUT as JSON or plain text.
- Human/informational messages, warnings and validation errors are printed to STDERR.
- Exit codes: `0` for success, non-zero for errors. Agents should check the exit code and parse STDOUT only on success.

How to provide model input (writes):
- Use `--model` to pass an inline JSON string, e.g.:
    `arledge customer create --model '{"name":"ACME","email":"x@acme.test"}'`
- Or use `--model-file` to pass a path to a JSON file, e.g.:
    `arledge customer create --model-file /tmp/customer.json`

How to discover JSON Schemas (important for agents):
- Per-command schema flag: add `--json-schema` to a create command to print that model's JSON Schema to STDOUT and exit.
    Example: `arledge customer create --json-schema`
- Global schema command: `arledge schema <name>` prints the named model's JSON Schema to stdout.
    Example: `arledge schema customer`
    Supported names: `customer`, `creditor`, `account`, `payment-account`, `invoice`, `invoice-line`.

Common read operations (machine-friendly):
- List customers: `arledge customer list`  # prints JSON array of customers to STDOUT
- View creditor: `arledge creditor view <id>`  # prints Creditor JSON to STDOUT
- List payment accounts: `arledge creditor account list [--creditor-id <id>]`
- Create invoice (write): use `--model` or `--model-file` with the `invoice create` command; created invoice JSON is printed to STDOUT and includes `invoice_number`.
- Export invoice JSON file: `arledge invoice export <id> --format json --path <file>`  # prints exported filepath to STDOUT

Agent guidelines and best practices:
- Always fetch the model JSON Schema first (via `--json-schema` or `arledge schema`) to know required fields and types before constructing `--model` input.
- Parse STDOUT as JSON on success; treat STDERR as human-facing logs only.
- Prefer non-destructive reads (list/view) before writes. When performing multi-step operations, run them in an isolated working directory and use the export command to confirm final state.
- Avoid concurrent writes to the same `ledger.db`; acquire external locks if needed.

Examples (agent-friendly):
- Get the Customer schema:
    `arledge customer create --json-schema`
    or

[36 more lines in file. Use offset=401 to continue.]"""
    click.echo(text, err=True)


@cli.command("schema")
@click.argument("name", type=str)
def schema(name):
    """Print Pydantic JSON Schema for a named model (customer, creditor, account, invoice).

    Example: `arledge schema customer` prints the Customer JSON Schema to stdout.
    """
    mapping = {
        "customer": models.Customer,
        "creditor": models.Creditor,
        "account": models.PaymentAccount,
        "payment-account": models.PaymentAccount,
        "invoice": models.Invoice,
        "invoice-line": getattr(models, "InvoiceLine", None),
    }
    if name not in mapping or mapping[name] is None:
        click.echo(
            "Unknown schema name. Available: customer, creditor, account, payment-account, invoice, invoice-line",
            err=True,
        )
        sys.exit(2)
    mdl = mapping[name]
    schema = mdl.model_json_schema()
    click.echo(json.dumps(schema, indent=2, ensure_ascii=False))


@cli.command("validate")
def validate():
    """Validate the full beancount ledger and detect orphan/missing invoice sidecars.

    Runs beancount.loader.load_file on ledger.beancount, reports parse errors,
    per-transaction balance violations (per currency), and invoice sidecar
    issues:
      - missing sidecar referenced by a transaction -> error
      - orphan sidecar present in includes/invoices/data not referenced -> warning

    Exits with code 0 on success, 2 on validation error.
    """
    from decimal import Decimal
    from pathlib import Path

    base = config.get_basedir()
    ledger_file = base / "ledger.beancount"
    if not ledger_file.exists():
        click.echo("No ledger.beancount found", err=True)
        sys.exit(2)
    try:
        from beancount.loader import load_file

        entries, errors, options = load_file(str(ledger_file))
    except Exception as e:
        click.echo(f"Failed to load ledger: {e}", err=True)
        sys.exit(2)

    had_error = False
    # Report parse/load errors. Treat unknown-account references as warnings.
    if errors:
        fatal = []
        warns = []
        for err in errors:
            s = None
            try:
                s = str(err)
            except Exception:
                s = repr(err)
            low = s.lower() if s else ""
            if "unknown account" in low or "invalid reference to unknown account" in low:
                warns.append(s)
            else:
                fatal.append(s)
        if fatal:
            click.echo("Beancount parse/load errors:", err=True)
            for err in fatal:
                click.echo(err, err=True)
            had_error = True
        if warns:
            click.echo("Beancount parse/load warnings:", err=True)
            for w in warns:
                click.echo(w, err=True)

    # Balance check: per-transaction, per-currency sums should be zero
    balance_issues = []
    for e in entries:
        if e.__class__.__name__ == "Transaction":
            sums: dict[str, Decimal] = {}
            postings = getattr(e, "postings", []) or []
            for p in postings:
                u = getattr(p, "units", None)
                if not u:
                    continue
                # attempt to extract numeric value
                num = None
                for attr in ("number", "value", "amount"):
                    num = getattr(u, attr, None)
                    if num is not None:
                        break
                if num is None:
                    try:
                        num = Decimal(str(u))
                    except Exception:
                        continue
                try:
                    dec = Decimal(str(num))
                except Exception:
                    try:
                        dec = Decimal(num)
                    except Exception:
                        continue
                cur = getattr(u, "currency", None) or getattr(u, "currency", None)
                if not cur:
                    cur = ""
                sums.setdefault(cur, Decimal(0))
                sums[cur] += dec
            for cur, total in sums.items():
                if total != Decimal(0):
                    balance_issues.append(
                        f"Unbalanced transaction {getattr(e,'date', '')} {getattr(e,'narration', '')}: currency={cur} total={total}"
                    )
    if balance_issues:
        click.echo("Balance issues detected:", err=True)
        for b in balance_issues:
            click.echo(b, err=True)
        had_error = True

    # Sidecar detection
    invoices_data = base / "includes" / "invoices" / "data"
    referenced = set()
    missing = []
    for e in entries:
        if e.__class__.__name__ == "Transaction":
            meta = getattr(e, "meta", {}) or {}
            inv_data = meta.get("invoice_data")
            if inv_data and isinstance(inv_data, str):
                p = Path(inv_data)
                if not p.is_absolute():
                    p = base / inv_data
                referenced.add(str(p.resolve()))
                if not p.exists():
                    missing.append(str(p))
    orphans = []
    try:
        if invoices_data.exists():
            for f in invoices_data.iterdir():
                if f.is_file():
                    if str(f.resolve()) not in referenced:
                        orphans.append(str(f))
    except Exception:
        pass

    if missing:
        click.echo("Missing invoice sidecars referenced by transactions:", err=True)
        for m in missing:
            click.echo(m, err=True)
        had_error = True

    if orphans:
        click.echo("Orphan invoice sidecars (present but not referenced):", err=True)
        for o in orphans:
            click.echo(o, err=True)

    if had_error:
        sys.exit(2)
    click.echo("Ledger OK", err=True)
