import click
import json
import sys
from . import db, models, config


@click.group()
def cli():
    """Ledger CLI

    AGENTS: run the `ledger instructions` command for detailed agent interaction instructions.

    Machine-actionable JSON is printed to stdout; human-facing messages
    and validation/file errors are printed to stderr. Validation and
    file-read errors exit with a non-zero code (the implementation
    currently uses ``sys.exit(2)`` for these error conditions).
    """
    pass


@cli.group()
def database():
    """Database commands"""
    pass


@database.command("initialize")
def initialize():
    """Initialize the database."""
    db_path = db.init_db()
    click.echo(f"Initialized database at {db_path}", err=True)


@cli.command("init")
@click.option("--force", is_flag=True, default=False, help="Overwrite existing beancount layout if present")
def init(force):
    """Initialize beancount-first directory layout for arledge (ledger.beancount, includes/, .arledge/).

    Creates the following structure in the current working directory:

      ledger.beancount
      includes/
        customers.beancount
        creditors.beancount
        payment_accounts.beancount
        invoices/
          YYYY-MM.beancount
          data/
      .arledge/
        invoice_seq

    If files/directories already exist the command will not overwrite them
    unless --force is provided.
    """
    from pathlib import Path
    import datetime

    cwd = Path.cwd()
    ledger_file = cwd / "ledger.beancount"
    includes_dir = cwd / "includes"
    includes_customers = includes_dir / "customers.beancount"
    includes_creditors = includes_dir / "creditors.beancount"
    includes_payment_accounts = includes_dir / "payment_accounts.beancount"
    invoices_dir = includes_dir / "invoices"
    invoices_data = invoices_dir / "data"
    arledge_dir = cwd / ".arledge"
    invoice_seq = arledge_dir / "invoice_seq"

    to_create = [includes_dir, invoices_dir, invoices_data, arledge_dir]

    # Check for existing files
    existing = []
    for p in [ledger_file, includes_customers, includes_creditors, includes_payment_accounts, invoices_dir, invoices_data, invoice_seq]:
        if p.exists():
            existing.append(str(p))

    if existing and not force:
        click.echo("Some target files or directories already exist:", err=True)
        for e in existing:
            click.echo(f"  {e}", err=True)
        click.echo("Run with --force to overwrite existing files where applicable.", err=True)
        sys.exit(2)

    # Create directories
    for d in to_create:
        d.mkdir(parents=True, exist_ok=True)

    # Write ledger.beancount with include directives
    ledger_contents = """; Top-level ledger file for arledge - generated by `ledger init`

include "includes/customers.beancount"
include "includes/creditors.beancount"
include "includes/payment_accounts.beancount"
include "includes/invoices/*.beancount"
"""
    ledger_file.write_text(ledger_contents, encoding="utf-8")

    # Write includes files if missing or forced
    if force or not includes_customers.exists():
        includes_customers.write_text(
            """; customers custom directives

; Example:
; 2026-03-01 custom "customer" "ACME Corp"
;   customer_id: 1
;   email: "sales@acme.example"

""",
            encoding="utf-8",
        )
    if force or not includes_creditors.exists():
        includes_creditors.write_text(
            """; creditors custom directives

; Example:
; 2026-03-01 custom "creditor" "Office Supplies Ltd"
;   creditor_id: 1
;   email: "billing@office.example"

""",
            encoding="utf-8",
        )
    if force or not includes_payment_accounts.exists():
        includes_payment_accounts.write_text(
            """; payment accounts custom directives

; Example:
; 2026-03-01 custom "payment_account" "Business Checking"
;   account_id: 1
;   bank: "Nordea"
;   iban: "SE1234567890"
;   currency: "SEK"

""",
            encoding="utf-8",
        )

    # create an empty current-month invoices file as an example
    now = datetime.date.today()
    month_file = invoices_dir / f"{now.year:04d}-{now.month:02d}.beancount"
    if force or not month_file.exists():
        month_file.write_text(
            f"; Invoices for {now.year:04d}-{now.month:02d}\n",
            encoding="utf-8",
        )

    # invoices data dir
    # ensure it's present (created above)

    # invoice_seq
    if force or not invoice_seq.exists():
        invoice_seq.write_text("1\n", encoding="utf-8")

    click.echo(f"Initialized beancount layout at {cwd}", err=True)


@cli.group()
def customer():
    """Customer commands"""
    pass


@customer.command("create")
@click.option("--model", "model_json", default="", help="JSON object for Customer")
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing Customer",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for Customer and exit",
)
def customer_create(model_json, model_file, json_schema):
    """Create a customer from a JSON model or file. Prints created customer JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(
                models.Customer.model_json_schema(), indent=2, ensure_ascii=False
            )
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        c = models.Customer.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid customer JSON: {e}", err=True)
        sys.exit(2)
    created = db.create_customer(c)
    # Actionable output: created customer as JSON on stdout
    click.echo(json.dumps(config.dump_model(created), ensure_ascii=False))


@customer.command("list")
def customer_list():
    customers = db.list_customers()
    if not customers:
        click.echo("No customers", err=True)
        return
    out = [config.dump_model(c) for c in customers]
    click.echo(json.dumps(out, ensure_ascii=False))


@cli.group()
def creditor():
    """Creditor (us) commands"""
    pass


@creditor.command("create")
@click.option("--model", "model_json", default="", help="JSON object for Creditor")
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing Creditor",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for Creditor and exit",
)
def creditor_create(model_json, model_file, json_schema):
    """Create a creditor from a JSON model or file. Prints created creditor JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(
                models.Creditor.model_json_schema(), indent=2, ensure_ascii=False
            )
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        cred = models.Creditor.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid creditor JSON: {e}", err=True)
        sys.exit(2)
    created = db.create_creditor(cred)
    click.echo(json.dumps(config.dump_model(created), ensure_ascii=False))


@creditor.command("list")
def creditor_list():
    creds = db.list_creditors()
    if not creds:
        click.echo("No creditors", err=True)
        return
    out = [config.dump_model(c) for c in creds]
    click.echo(json.dumps(out, ensure_ascii=False))


@creditor.command("view")
@click.argument("creditor_id", type=int)
def creditor_view(creditor_id):
    c = db.get_creditor(creditor_id)
    if not c:
        click.echo("Creditor not found", err=True)
        sys.exit(2)
    click.echo(json.dumps(config.dump_model(c), ensure_ascii=False))


@creditor.group()
def account():
    """Creditor inbound payment accounts"""
    pass


@account.command("create")
@click.option(
    "--model", "model_json", default="", help="JSON object for PaymentAccount"
)
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing PaymentAccount",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for PaymentAccount and exit",
)
def account_create(model_json, model_file, json_schema):
    """Create a payment account from a JSON model or file. Prints created account JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(
                models.PaymentAccount.model_json_schema(), indent=2, ensure_ascii=False
            )
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        pa = models.PaymentAccount.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid payment account JSON: {e}", err=True)
        sys.exit(2)
    created = db.create_payment_account(pa)
    click.echo(json.dumps(config.dump_model(created), ensure_ascii=False))


@account.command("list")
@click.option("--creditor-id", type=int, default=None)
def account_list(creditor_id):
    rows = db.list_payment_accounts(creditor_id=creditor_id)
    if not rows:
        click.echo("No payment accounts", err=True)
        return
    out = [config.dump_model(r) for r in rows]
    click.echo(json.dumps(out, ensure_ascii=False))


@cli.group()
def invoice():
    """Invoice commands"""
    pass


@invoice.command("create")
@click.option("--model", "model_json", default="", help="JSON object for Invoice")
@click.option(
    "--model-file",
    "model_file",
    type=click.Path(exists=True),
    default=None,
    help="Path to JSON file containing Invoice",
)
@click.option(
    "--json-schema",
    "json_schema",
    is_flag=True,
    default=False,
    help="Print Pydantic JSON Schema for Invoice and exit",
)
def invoice_create(model_json, model_file, json_schema):
    """Create an invoice from a JSON model or file. Prints created invoice JSON to stdout."""
    if json_schema:
        click.echo(
            json.dumps(models.Invoice.model_json_schema(), indent=2, ensure_ascii=False)
        )
        return

    if model_file:
        try:
            with open(model_file, "r", encoding="utf-8") as f:
                model_json = f.read()
        except Exception as e:
            click.echo(f"Failed to read model file: {e}", err=True)
            sys.exit(2)
    if not model_json:
        click.echo("Provide --model JSON or --model-file", err=True)
        sys.exit(2)
    try:
        inv = models.Invoice.model_validate_json(model_json)
    except Exception as e:
        click.echo(f"Invalid invoice JSON: {e}", err=True)
        sys.exit(2)
    created = db.create_invoice(inv)
    # Include invoice id and invoice_number in actionable JSON
    out = config.dump_model(created)
    out["invoice_number"] = db.format_invoice_number(created.id)
    click.echo(json.dumps(out, ensure_ascii=False))


@invoice.command("list")
def invoice_list():
    invs = db.list_invoices()
    if not invs:
        click.echo("No invoices", err=True)
        return
    out = [config.dump_model(inv) for inv in invs]
    click.echo(json.dumps(out, ensure_ascii=False))


@invoice.command("view")
@click.argument("invoice_id", type=int)
def invoice_view(invoice_id):
    inv = db.get_invoice(invoice_id)
    if not inv:
        click.echo("Invoice not found", err=True)
        sys.exit(2)
    click.echo(json.dumps(config.dump_model(inv), ensure_ascii=False))


@invoice.command("export")
@click.argument("invoice_id", type=int)
@click.option("--format", "fmt", type=click.Choice(["json", "text"]), default="json")
@click.option("--path", default=None)
def invoice_export(invoice_id, fmt, path):
    if fmt == "json":
        out = db.export_invoice_json(invoice_id, path=path)
        if not out:
            click.echo("Invoice not found", err=True)
            sys.exit(2)
        # actionable output: exported filepath on stdout
        click.echo(out)
    else:
        click.echo("Text export not implemented yet", err=True)
        sys.exit(2)


@cli.group()
def mcp():
    """MCP server commands (stdio transport using FastMCP)."""
    pass


@mcp.command("start")
@click.option("--name", default=None, help="Optional name for the MCP server")
@click.option(
    "--json-response/--no-json-response",
    default=config.MCP_JSON_RESPONSE,
    help="Prefer JSON responses where supported",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Validate configuration and exit without starting the server",
)
def mcp_start(name, json_response, dry_run):
    """Start an MCP stdio server using the official `mcp` library (blocks).

    Example: `uv run python -m ledger mcp start` will block and listen on
    stdin/stdout. Use `--dry-run` to validate imports and configuration
    without blocking (useful for tests).
    """
    # Lazy import to avoid requiring mcp at module import time for unrelated CLI commands
    try:
        from .mcp_server import start_mcp_stdio_server
    except Exception as e:
        click.echo(f"Failed to load MCP server launcher: {e}", err=True)
        sys.exit(2)

    # Call launcher; when not dry-run this will block (mcp.run)
    try:
        start_mcp_stdio_server(name=name, json_response=json_response, dry_run=dry_run)
    except Exception:
        click.echo("Failed to start MCP server", err=True)
        sys.exit(2)


@cli.command()
def instructions():
    """Print instructions for agentic systems on interacting with the CLI."""
    text = """Instructions for agentic systems interacting with the ledger CLI

Overview and machine I/O conventions:
- All machine-actionable outputs (created/listed models, schemas, export file paths) are printed to STDOUT as JSON or plain text.
- Human/informational messages, warnings and validation errors are printed to STDERR.
- Exit codes: `0` for success, non-zero for errors. Agents should check the exit code and parse STDOUT only on success.

How to provide model input (writes):
- Use `--model` to pass an inline JSON string, e.g.:
    `python -m ledger customer create --model '{"name":"ACME","email":"x@acme.test"}'`
- Or use `--model-file` to pass a path to a JSON file, e.g.:
    `python -m ledger customer create --model-file /tmp/customer.json`

How to discover JSON Schemas (important for agents):
- Per-command schema flag: add `--json-schema` to a create command to print that model's JSON Schema to STDOUT and exit.
    Example: `python -m ledger customer create --json-schema`
- Global schema command: `python -m ledger schema <name>` prints the named model's JSON Schema to stdout.
    Example: `python -m ledger schema customer`
    Supported names: `customer`, `creditor`, `account`, `payment-account`, `invoice`, `invoice-line`.

Common read operations (machine-friendly):
- List customers: `python -m ledger customer list`  # prints JSON array of customers to STDOUT
- View creditor: `python -m ledger creditor view <id>`  # prints Creditor JSON to STDOUT
- List payment accounts: `python -m ledger creditor account list [--creditor-id <id>]`
- Create invoice (write): use `--model` or `--model-file` with the `invoice create` command; created invoice JSON is printed to STDOUT and includes `invoice_number`.
- Export invoice JSON file: `python -m ledger invoice export <id> --format json --path <file>`  # prints exported filepath to STDOUT

Agent guidelines and best practices:
- Always fetch the model JSON Schema first (via `--json-schema` or `ledger schema`) to know required fields and types before constructing `--model` input.
- Parse STDOUT as JSON on success; treat STDERR as human-facing logs only.
- Prefer non-destructive reads (list/view) before writes. When performing multi-step operations, run them in an isolated working directory and use the export command to confirm final state.
- Avoid concurrent writes to the same `ledger.db`; acquire external locks if needed.

Examples (agent-friendly):
- Get the Customer schema:
    `python -m ledger customer create --json-schema`
    or

[36 more lines in file. Use offset=401 to continue.]"""
    click.echo(text, err=True)


@cli.command("schema")
@click.argument("name", type=str)
def schema(name):
    """Print Pydantic JSON Schema for a named model (customer, creditor, account, invoice).

    Example: `python -m ledger schema customer` prints the Customer JSON Schema to stdout.
    """
    mapping = {
        "customer": models.Customer,
        "creditor": models.Creditor,
        "account": models.PaymentAccount,
        "payment-account": models.PaymentAccount,
        "invoice": models.Invoice,
        "invoice-line": getattr(models, "InvoiceLine", None),
    }
    if name not in mapping or mapping[name] is None:
        click.echo(
            "Unknown schema name. Available: customer, creditor, account, payment-account, invoice, invoice-line",
            err=True,
        )
        sys.exit(2)
    mdl = mapping[name]
    schema = mdl.model_json_schema()
    click.echo(json.dumps(schema, indent=2, ensure_ascii=False))
